amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan
    min_particles: 100
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    update_min_d: 0.25
    update_min_a: 0.2
    laser_max_range: 8.0
    set_initial_pose: true

# map_server:
#   ros__parameters:
#     use_sim_time: false
#     yaml_filename: "map.yaml"  # Замените на путь к вашей карте

# map_saver:
#   ros__parameters:
#     use_sim_time: false
#     save_map_timeout: 5.0
#     free_thresh: 0.25
#     occupied_thresh: 0.65
#     map_subscribe_transient_local: true

# bt_navigator:
#   ros__parameters:
#     use_sim_time: false
#     default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"
#     behavior_tree_plugins: ["nav2_behaviors/Spin", "nav2_behaviors/BackUp", "nav2_behaviors/Wait"]
#     plugin_lib_names:
#       - nav2_compute_path_to_pose_action_bt_node
#       - nav2_follow_path_action_bt_node
#       - nav2_recovery_node_bt_node
#       - nav2_is_path_valid_condition_bt_node

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    bt_loop_duration: 10
    filter_duration: 0.3
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    service_introspection_mode: "disabled"
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
      enable_groot_monitoring: false
      groot_server_port: 1667
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
      enable_groot_monitoring: false
      groot_server_port: 1669

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.05
      max_linear_accel: 0.15
      lookahead_dist: 0.4
      min_lookahead_dist: 0.1
      max_lookahead_dist: 0.8
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading_angular_vel: 0.25
      transform_tolerance: 0.2
    min_vel_x: 0.01
    max_vel_x: 0.04
    max_vel_theta: 0.25
    # cmd_vel_topic: /diffbot_base_controller/cmd_vel

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.1
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: laser
        laser:
          topic: scan
          max_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: LaserScan
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      width: 5
      height: 5
      robot_radius: 0.1
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: laser
        laser:
          topic: scan
          max_obstacle_height: 0.5
          clearing: true
          marking: true
          data_type: LaserScan
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25

recoveries_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: true
    loop_rate: 20