slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    use_sim_time: false
    resolution: 0.05
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_publish_period: 1.0
    map_update_interval: 2.0
    max_laser_range: 10.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174 # ~10 degrees
    scan_matching_timeout: 1.0
    tf_buffer_duration: 30.0
    # for small maze, high accuracy
    map_start_pose: [0.0, 0.0, 0.0]
    use_scan_matching: true
    # Optional for multi-robot: remap map_topic